In [ ]:
## import libraries
import glob
import xarray as xr
import geopandas as gpd
import os
import re
from collections import defaultdict
import pandas as pd
from pathlib import Path
import gc

In [ ]:
source_dir = '/Volumes/T7/data/blanka/'
files = sorted(glob.glob(source_dir + 'C1/*.nc'))
files2 = sorted(glob.glob(source_dir + 'C2/*.nc'))

In [ ]:
def yield_files_by_month(file_list, date_pattern):

    # Dictionary to hold the groups: Key = (2024, 8), Value = [file1, file2...]
    grouped_files = defaultdict(list)

    for file_path in file_list:
        filename = os.path.basename(file_path)
        match = date_pattern.search(filename)
        
        if match:
            year = int(match.group(1))
            month = int(match.group(2))
            grouped_files[(year, month)].append(file_path)
        else:
            print(f"Warning: Could not parse date from {filename}")

    for (year, month), files in grouped_files.items():
        yield (year, month), files

In [ ]:
def convert_nc_to_parquet(file_list, columns):
    """
    Reads a list of EarthCARE NC files, converts them to a GeoDataFrame,
    sorts by time and location, and saves as GeoParquet.
    """
    dataframes = []

    print(f"Processing {len(file_list)} files...")

    for file_path in file_list:
        try:
            # Open the NetCDF file
            with xr.open_dataset(file_path, decode_timedelta=True) as ds:

                # Convert to Pandas DataFrame
                subset = ds[columns]
                df = subset.to_dataframe().reset_index(drop=True)

                # Extract EarthCARE ID
                path_obj = Path(file_path)
                earthcare_id = path_obj.stem.split('_')[-1]                
                df['earthcare_id'] = earthcare_id

                # add to list
                dataframes.append(df)

        except Exception as e:
            print(f"Error processing file {file_path}: {e}")


    print("Concatenating data...")
    full_df = pd.concat(dataframes, ignore_index=True)

    del dataframes
    gc.collect()


    print("Converting to GeoDataFrame...")
    # Create the geometry column from coordinates
    geometry = gpd.points_from_xy(full_df['longitude'], full_df['latitude'])
    gdf = gpd.GeoDataFrame(full_df, geometry=geometry, crs="EPSG:4326")

    del full_df
    gc.collect()

    print("Sorting data...")
    gdf.sort_values(
        by=['geometry', 'group_time'], 
        inplace=True, 
        ignore_index=True
    )

    return gdf

### Collection 1

Convert and store the GLM files

In [ ]:
output_dir = '/Volumes/T7/data/blanka/C1_parquet/'
source = 'GLM'
date_pattern = re.compile(r"GLM_(\d{4})(\d{2})")
source_files = [f for f in files if source in f]
columns = ['group_id',
 'group_time',
 'latitude',
 'longitude',
 'radiance',
 'flash_id',
 'ec_time_diff',
 'parent_cluster_id',
 'cluster_id',
 'distance_from_nadir']

earthcare_ids = {}

for ((year, month), filelist) in yield_files_by_month(source_files, date_pattern):
    gdf = convert_nc_to_parquet(filelist, columns)
    gdf['source'] = source
    gdf.to_parquet(
        output_dir + f'{source}_{year}_{month}.parquet',
        engine='pyarrow',
        compression='zstd',
        write_covering_bbox=True, 
        schema_version='1.1.0'
    )
    for id in gdf['earthcare_id'].unique():
        earthcare_ids.setdefault(id, []).append(f'{source}_{year}_{month}.parquet')

Processing 381 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 286 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 248 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 253 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 232 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 275 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 262 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 304 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 368 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 362 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 344 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 383 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 420 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 406 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 319 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 354 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 361 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 354 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...

Convert and store the LI files

In [ ]:
output_dir = '/Volumes/T7/data/blanka/C1_parquet/'
source = 'LI'
date_pattern = re.compile(r"LI_(\d{4})(\d{2})")
source_files = [f for f in files if source in f]
columns = ['group_id',
 'group_time',
 'latitude',
 'longitude',
 'radiance',
 'flash_id',
 'parallax_corrected_lat',
 'parallax_corrected_lon',
 'ec_time_diff',
 'parent_cluster_id',
 'cluster_id',
 'distance_from_nadir']


for ((year, month), filelist) in yield_files_by_month(source_files, date_pattern):
    gdf = convert_nc_to_parquet(filelist,columns)
    gdf['source'] = source
    gdf.to_parquet(
        output_dir + f'{source}_{year}_{month}.parquet',
        engine='pyarrow',
        compression='zstd',
        write_covering_bbox=True, 
        schema_version='1.1.0'
    )
    
    for id in gdf['earthcare_id'].unique():
        earthcare_ids.setdefault(id, []).append(f'{source}_{year}_{month}.parquet')

Processing 305 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 244 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 201 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 221 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 220 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 290 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 267 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 313 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 337 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 340 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 286 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 324 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 348 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 292 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 216 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 298 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 304 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...
Processing 311 files...
Concatenating data...
Converting to GeoDataFrame...
Sorting data...

In [ ]:
earthcare_ids

{'01253H': ['GLM_2024_8.parquet'],
 '01042F': ['GLM_2024_8.parquet'],
 '01206H': ['GLM_2024_8.parquet'],
 '01214F': ['GLM_2024_8.parquet'],
 '01283H': ['GLM_2024_8.parquet'],
 '01112H': ['GLM_2024_8.parquet'],
 '01190H': ['GLM_2024_8.parquet'],
 '01019H': ['GLM_2024_8.parquet'],
 '01089F': ['GLM_2024_8.parquet'],
 '01035H': ['GLM_2024_8.parquet'],
 '01057F': ['GLM_2024_8.parquet'],
 '01088F': ['GLM_2024_8.parquet'],
 '01080H': ['GLM_2024_8.parquet'],
 '01350F': ['GLM_2024_8.parquet'],
 '01023F': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01093H': ['GLM_2024_8.parquet'],
 '01085F': ['GLM_2024_8.parquet'],
 '01155H': ['GLM_2024_8.parquet'],
 '01015H': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01046H': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01170H': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01248H': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01178F': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01279H': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01302F': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01395F': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01193F': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01185H': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01216H': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01317F': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01131F': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01388H': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01365F': ['GLM_2024_8.parquet'],
 '01295H': ['GLM_2024_8.parquet'],
 '01334F': ['GLM_2024_8.parquet'],
 '01303F': ['GLM_2024_8.parquet'],
 '01101F': ['GLM_2024_8.parquet'],
 '01031H': ['GLM_2024_8.parquet'],
 '01474F': ['GLM_2024_8.parquet'],
 '01256F': ['GLM_2024_8.parquet'],
 '01326H': ['GLM_2024_8.parquet'],
 '01311H': ['GLM_2024_8.parquet'],
 '01397E': ['GLM_2024_8.parquet'],
 '01475E': ['GLM_2024_8.parquet'],
 '01079A': ['GLM_2024_8.parquet'],
 '01055E': ['GLM_2024_8.parquet'],
 '01250A': ['GLM_2024_8.parquet'],
 '01366E': ['GLM_2024_8.parquet'],
 '01281A': ['GLM_2024_8.parquet'],
 '01110A': ['GLM_2024_8.parquet'],
 '01117E': ['GLM_2024_8.parquet'],
 '01086E': ['GLM_2024_8.parquet'],
 '01288E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01039E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01241E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01132E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01132F': ['GLM_2024_8.parquet'],
 '01101E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01063A': ['GLM_2024_8.parquet'],
 '01343A': ['GLM_2024_8.parquet'],
 '01365E': ['GLM_2024_8.parquet'],
 '01358A': ['GLM_2024_8.parquet'],
 '01357H': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01007E': ['GLM_2024_8.parquet'],
 '01007F': ['GLM_2024_8.parquet'],
 '01396E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01163E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01023E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01412E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01156A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01125A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01179E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01405A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01459E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01265A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01148E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01008E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01257E': ['GLM_2024_8.parquet'],
 '01203A': ['GLM_2024_8.parquet'],
 '01374A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01210E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01001A': ['GLM_2024_8.parquet'],
 '01032A': ['GLM_2024_8.parquet'],
 '01381E': ['GLM_2024_8.parquet'],
 '01467A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01194E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01319E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01234A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01141A': ['GLM_2024_8.parquet'],
 '01390A': ['GLM_2024_8.parquet'],
 '01304E': ['GLM_2024_8.parquet'],
 '01133E': ['GLM_2024_8.parquet'],
 '01273E': ['GLM_2024_8.parquet'],
 '01102E': ['GLM_2024_8.parquet'],
 '01413E': ['GLM_2024_8.parquet'],
 '01335E': ['GLM_2024_8.parquet'],
 '01312A': ['GLM_2024_8.parquet'],
 '01048A': ['GLM_2024_8.parquet'],
 '01164E': ['GLM_2024_8.parquet'],
 '01320E': ['GLM_2024_8.parquet'],
 '01382E': ['GLM_2024_8.parquet'],
 '01359A': ['GLM_2024_8.parquet'],
 '01024E': ['GLM_2024_8.parquet'],
 '01195E': ['GLM_2024_8.parquet'],
 '01172A': ['GLM_2024_8.parquet'],
 '01213E': ['GLM_2024_8.parquet'],
 '01391A': ['GLM_2024_8.parquet'],
 '01025E': ['GLM_2024_8.parquet'],
 '01476E': ['GLM_2024_8.parquet'],
 '01336E': ['GLM_2024_8.parquet'],
 '01196E': ['GLM_2024_8.parquet'],
 '01090E': ['GLM_2024_8.parquet'],
 '01208A': ['GLM_2024_8.parquet'],
 '01301A': ['GLM_2024_8.parquet'],
 '01052A': ['GLM_2024_8.parquet'],
 '01021A': ['GLM_2024_8.parquet'],
 '01425A': ['GLM_2024_8.parquet'],
 '01083A': ['GLM_2024_8.parquet'],
 '01005A': ['GLM_2024_8.parquet'],
 '01316A': ['GLM_2024_8.parquet'],
 '01238A': ['GLM_2024_8.parquet'],
 '01192A': ['GLM_2024_8.parquet'],
 '01393A': ['GLM_2024_8.parquet'],
 '01244E': ['GLM_2024_8.parquet'],
 '01205A': ['GLM_2024_8.parquet'],
 '01345A': ['GLM_2024_8.parquet'],
 '01313A': ['GLM_2024_8.parquet'],
 '01344A': ['GLM_2024_8.parquet'],
 '01087E': ['GLM_2024_8.parquet'],
 '01227E': ['GLM_2024_8.parquet'],
 '01173A': ['GLM_2024_8.parquet'],
 '01165E': ['GLM_2024_8.parquet'],
 '01367E': ['GLM_2024_8.parquet'],
 '01305E': ['GLM_2024_8.parquet'],
 '01111A': ['GLM_2024_8.parquet'],
 '01251A': ['GLM_2024_8.parquet'],
 '01103E': ['GLM_2024_8.parquet'],
 '01360A': ['GLM_2024_8.parquet'],
 '01352E': ['GLM_2024_8.parquet'],
 '01181E': ['GLM_2024_8.parquet'],
 '01469A': ['GLM_2024_8.parquet'],
 '01127A': ['GLM_2024_8.parquet'],
 '01150E': ['GLM_2024_8.parquet'],
 '01010E': ['GLM_2024_8.parquet'],
 '01041E': ['GLM_2024_8.parquet'],
 '01212E': ['GLM_2024_8.parquet'],
 '01049A': ['GLM_2024_8.parquet'],
 '01243E': ['GLM_2024_8.parquet'],
 '01329A': ['GLM_2024_8.parquet'],
 '01189A': ['GLM_2024_8.parquet'],
 '01414E': ['GLM_2024_8.parquet'],
 '01274E': ['GLM_2024_8.parquet'],
 '01422A': ['GLM_2024_8.parquet'],
 '01282A': ['GLM_2024_8.parquet'],
 '01033A': ['GLM_2024_8.parquet'],
 '01002A': ['GLM_2024_8.parquet'],
 '01235A': ['GLM_2024_8.parquet'],
 '01375A': ['GLM_2024_8.parquet'],
 '01064A': ['GLM_2024_8.parquet'],
 '01383E': ['GLM_2024_8.parquet'],
 '01220A': ['GLM_2024_8.parquet'],
 '01142A': ['GLM_2024_8.parquet'],
 '01134E': ['GLM_2024_8.parquet'],
 '01204A': ['GLM_2024_8.parquet'],
 '01056E': ['GLM_2024_8.parquet'],
 '01321E': ['GLM_2024_8.parquet'],
 '01298A': ['GLM_2024_8.parquet'],
 '01290E': ['GLM_2024_8.parquet'],
 '01259E': ['GLM_2024_8.parquet'],
 '01267A': ['GLM_2024_8.parquet'],
 '01065A': ['GLM_2024_8.parquet'],
 '01228E': ['GLM_2024_8.parquet'],
 '01034A': ['GLM_2024_8.parquet'],
 '01252A': ['GLM_2024_8.parquet'],
 '01423A': ['GLM_2024_8.parquet'],
 '01221A': ['GLM_2024_8.parquet'],
 '01019A': ['GLM_2024_8.parquet'],
 '01477E': ['GLM_2024_8.parquet'],
 '01461E': ['GLM_2024_8.parquet'],
 '01072E': ['GLM_2024_8.parquet'],
 '01352D': ['GLM_2024_8.parquet'],
 '01072D': ['GLM_2024_8.parquet'],
 '01243D': ['GLM_2024_8.parquet'],
 '01383D': ['GLM_2024_8.parquet'],
 '01414D': ['GLM_2024_8.parquet'],
 '01196D': ['GLM_2024_8.parquet'],
 '01025D': ['GLM_2024_8.parquet'],
 '01056D': ['GLM_2024_8.parquet'],
 '01476D': ['GLM_2024_8.parquet'],
 '01033B': ['GLM_2024_8.parquet'],
 '01204B': ['GLM_2024_8.parquet'],
 '01305D': ['GLM_2024_8.parquet'],
 '01375B': ['GLM_2024_8.parquet'],
 '01173B': ['GLM_2024_8.parquet'],
 '01313B': ['GLM_2024_8.parquet'],
 '01282B': ['GLM_2024_8.parquet'],
 '01142B': ['GLM_2024_8.parquet'],
 '01461D': ['GLM_2024_8.parquet'],
 '01251B': ['GLM_2024_8.parquet'],
 '01212D': ['GLM_2024_8.parquet'],
 '01181D': ['GLM_2024_8.parquet'],
 '01220B': ['GLM_2024_8.parquet'],
 '01010D': ['GLM_2024_8.parquet'],
 '01360B': ['GLM_2024_8.parquet'],
 '01329B': ['GLM_2024_8.parquet'],
 '01189B': ['GLM_2024_8.parquet'],
 '01469B': ['GLM_2024_8.parquet'],
 '01049B': ['GLM_2024_8.parquet'],
 '01150D': ['GLM_2024_8.parquet'],
 '01018B': ['GLM_2024_8.parquet'],
 '01041D': ['GLM_2024_8.parquet'],
 '01298B': ['GLM_2024_8.parquet'],
 '01158B': ['GLM_2024_8.parquet'],
 '01088D': ['GLM_2024_8.parquet'],
 '01088E': ['GLM_2024_8.parquet'],
 '01368D': ['GLM_2024_8.parquet'],
 '01368E': ['GLM_2024_8.parquet'],
 '01228D': ['GLM_2024_8.parquet'],
 '01477D': ['GLM_2024_8.parquet'],
 '01119D': ['GLM_2024_8.parquet'],
 '01259D': ['GLM_2024_8.parquet'],
 '01399D': ['GLM_2024_8.parquet'],
 '01290D': ['GLM_2024_8.parquet'],
 '01422B': ['GLM_2024_8.parquet'],
 '01274D': ['GLM_2024_8.parquet'],
 '01235B': ['GLM_2024_8.parquet'],
 '01064B': ['GLM_2024_8.parquet'],
 '01165D': ['GLM_2024_8.parquet'],
 '01095B': ['GLM_2024_8.parquet'],
 '01126B': ['GLM_2024_8.parquet'],
 '01197D': ['GLM_2024_8.parquet'],
 '01166D': ['GLM_2024_8.parquet'],
 '01471B': ['GLM_2024_8.parquet'],
 '01417D': ['GLM_2024_8.parquet'],
 '01472A': ['GLM_2024_8.parquet'],
 '01300B': ['GLM_2024_8.parquet'],
 '01059D': ['GLM_2024_8.parquet'],
 '01260D': ['GLM_2024_8.parquet'],
 '01042D': ['GLM_2024_8.parquet'],
 '01353D': ['GLM_2024_8.parquet'],
 '01073D': ['GLM_2024_8.parquet'],
 '01275D': ['GLM_2024_8.parquet'],
 '01135D': ['GLM_2024_8.parquet'],
 '01065B': ['GLM_2024_8.parquet'],
 '01151D': ['GLM_2024_8.parquet'],
 '01104D': ['GLM_2024_8.parquet'],
 '01244D': ['GLM_2024_8.parquet'],
 '01182D': ['GLM_2024_8.parquet'],
 '01127B': ['GLM_2024_8.parquet'],
 '01080B': ['GLM_2024_8.parquet'],
 '01306D': ['GLM_2024_8.parquet'],
 '01328B': ['GLM_2024_8.parquet'],
 '01391B': ['GLM_2024_8.parquet'],
 '01337D': ['GLM_2024_8.parquet'],
 '01057D': ['GLM_2024_8.parquet'],
 '01111B': ['GLM_2024_8.parquet'],
 '01026D': ['GLM_2024_8.parquet'],
 '01096B': ['GLM_2024_8.parquet'],
 '01227D': ['GLM_2024_8.parquet'],
 '01367D': ['GLM_2024_8.parquet'],
 '01048B': ['GLM_2024_8.parquet'],
 '01118D': ['GLM_2024_8.parquet'],
 '01398D': ['GLM_2024_8.parquet'],
 '01289D': ['GLM_2024_8.parquet'],
 '01149D': ['GLM_2024_8.parquet'],
 '01110B': ['GLM_2024_8.parquet'],
 '01320D': ['GLM_2024_8.parquet'],
 '01359B': ['GLM_2024_8.parquet'],
 '01390B': ['GLM_2024_8.parquet'],
 '01281B': ['GLM_2024_8.parquet'],
 '01258D': ['GLM_2024_8.parquet'],
 '01009D': ['GLM_2024_8.parquet'],
 '01079B': ['GLM_2024_8.parquet'],
 '01180D': ['GLM_2024_8.parquet'],
 '01001B': ['GLM_2024_8.parquet'],
 '01312B': ['GLM_2024_8.parquet'],
 '01351D': ['GLM_2024_8.parquet'],
 '01032B': ['GLM_2024_8.parquet'],
 '01343B': ['GLM_2024_8.parquet'],
 '01203B': ['GLM_2024_8.parquet'],
 '01071D': ['GLM_2024_8.parquet'],
 '01040D': ['GLM_2024_8.parquet'],
 '01460D': ['GLM_2024_8.parquet'],
 '01141B': ['GLM_2024_8.parquet'],
 '01172B': ['GLM_2024_8.parquet'],
 '01063B': ['GLM_2024_8.parquet'],
 '01382D': ['GLM_2024_8.parquet'],
 '01405B': ['GLM_2024_8.parquet'],
 '01133D': ['GLM_2024_8.parquet'],
 '01304D': ['GLM_2024_8.parquet'],
 '01211D': ['GLM_2024_8.parquet'],
 '01055D': ['GLM_2024_8.parquet'],
 '01226D': ['GLM_2024_8.parquet'],
 '01195D': ['GLM_2024_8.parquet'],
 '01257D': ['GLM_2024_8.parquet'],
 '01218B': ['GLM_2024_8.parquet'],
 '01459D': ['GLM_2024_8.parquet'],
 '01420B': ['GLM_2024_8.parquet'],
 '01202B': ['GLM_2024_8.parquet'],
 '01187B': ['GLM_2024_8.parquet'],
 '01467B': ['GLM_2024_8.parquet'],
 '01249B': ['GLM_2024_8.parquet'],
 '01335D': ['GLM_2024_8.parquet'],
 '01327B': ['GLM_2024_8.parquet'],
 '01164D': ['GLM_2024_8.parquet'],
 '01047B': ['GLM_2024_8.parquet'],
 '01366D': ['GLM_2024_8.parquet'],
 '01358B': ['GLM_2024_8.parquet'],
 '01264B': ['GLM_2024_8.parquet'],
 '01124B': ['GLM_2024_8.parquet'],
 '01233B': ['GLM_2024_8.parquet'],
 '01000B': ['GLM_2024_8.parquet'],
 '01093B': ['GLM_2024_8.parquet'],
 '01086D': ['GLM_2024_8.parquet'],
 '01413D': ['GLM_2024_8.parquet'],
 '01296B': ['GLM_2024_8.parquet'],
 '01094B': ['GLM_2024_8.parquet'],
 '01017B': ['GLM_2024_8.parquet'],
 '01468B': ['GLM_2024_8.parquet'],
 '01087D': ['GLM_2024_8.parquet'],
 '01250B': ['GLM_2024_8.parquet'],
 '01242D': ['GLM_2024_8.parquet'],
 '01134D': ['GLM_2024_8.parquet'],
 '01466B': ['GLM_2024_8.parquet'],
 '01381D': ['GLM_2024_8.parquet'],
 '01256D': ['GLM_2024_8.parquet'],
 '01139B': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01061B': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01046B': ['GLM_2024_8.parquet'],
 '01474D': ['GLM_2024_8.parquet'],
 '01365D': ['GLM_2024_8.parquet'],
 '01287E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01140A': ['GLM_2024_8.parquet'],
 '01389A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01148D': ['GLM_2024_8.parquet'],
 '01297B': ['GLM_2024_8.parquet'],
 '01040E': ['GLM_2024_8.parquet'],
 '01289E': ['GLM_2024_8.parquet'],
 '01017A': ['GLM_2024_8.parquet'],
 '01258E': ['GLM_2024_8.parquet'],
 '01398E': ['GLM_2024_8.parquet'],
 '01266A': ['GLM_2024_8.parquet'],
 '01266B': ['GLM_2024_8.parquet'],
 '01406A': ['GLM_2024_8.parquet'],
 '01126A': ['GLM_2024_8.parquet'],
 '01118E': ['GLM_2024_8.parquet'],
 '01149E': ['GLM_2024_8.parquet'],
 '01009E': ['GLM_2024_8.parquet'],
 '01188A': ['GLM_2024_8.parquet'],
 '01180E': ['GLM_2024_8.parquet'],
 '01460E': ['GLM_2024_8.parquet'],
 '01421A': ['GLM_2024_8.parquet'],
 '01242E': ['GLM_2024_8.parquet'],
 '01351E': ['GLM_2024_8.parquet'],
 '01211E': ['GLM_2024_8.parquet'],
 '01071E': ['GLM_2024_8.parquet'],
 '01468A': ['GLM_2024_8.parquet'],
 '01297A': ['GLM_2024_8.parquet'],
 '01157A': ['GLM_2024_8.parquet'],
 '01095A': ['GLM_2024_8.parquet'],
 '01328A': ['GLM_2024_8.parquet'],
 '01265B': ['GLM_2024_8.parquet'],
 '01420A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01219A': ['GLM_2024_8.parquet'],
 '01233A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01271E': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01046A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01404A': ['GLM_2024_8.parquet', 'LI_2024_8.parquet'],
 '01093A': ['GLM_2024_8.parquet'],
 '01373A': ['GLM_2024_8.parquet'],
 '01348B': ['GLM_2024_8.parquet'],
 '01006B': ['GLM_2024_8.parquet'],
 '01379B': ['GLM_2024_8.parquet'],
 '01317B': ['GLM_2024_8.parquet'],
 '01317A': ['GLM_2024_8.parquet'],
 '01286A': ['GLM_2024_8.parquet'],
 '01395A': ['GLM_2024_8.parquet'],
 '01255A': ['GLM_2024_8.parquet'],
 '01115A': ['GLM_2024_8.parquet'],
 '01084A': ['GLM_2024_8.parquet'],
 '01146A': ['GLM_2024_8.parquet'],
 '01860H': ['GLM_2024_9.parquet'],
 '01751H': ['GLM_2024_9.parquet'],
 '01928F': ['GLM_2024_9.parquet'],
 '01632F': ['GLM_2024_9.parquet'],
 '01654H': ['GLM_2024_9.parquet'],
 '01933H': ['GLM_2024_9.parquet'],
 '01544H': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01855H': ['GLM_2024_9.parquet'],
 '01629F': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01559H': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01730H': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01886H': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01785F': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01676F': ['GLM_2024_9.parquet'],
 '01863F': ['GLM_2024_9.parquet'],
 '01832F': ['GLM_2024_9.parquet'],
 '01871H': ['GLM_2024_9.parquet'],
 '01941F': ['GLM_2024_9.parquet'],
 '01840H': ['GLM_2024_9.parquet'],
 '01739F': ['GLM_2024_9.parquet'],
 '01614F': ['GLM_2024_9.parquet'],
 '01645F': ['GLM_2024_9.parquet'],
 '01684H': ['GLM_2024_9.parquet'],
 '01536F': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01646E': ['GLM_2024_9.parquet'],
 '01786E': ['GLM_2024_9.parquet'],
 '01755E': ['GLM_2024_9.parquet'],
 '01942E': ['GLM_2024_9.parquet'],
 '01724E': ['GLM_2024_9.parquet'],
 '01864E': ['GLM_2024_9.parquet'],
 '01584E': ['GLM_2024_9.parquet'],
 '01888A': ['GLM_2024_9.parquet'],
 '01895E': ['GLM_2024_9.parquet'],
 '01670A': ['GLM_2024_9.parquet'],
 '01926E': ['GLM_2024_9.parquet'],
 '01537E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01677E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01568E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01692E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01794A': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01879E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01701A': ['GLM_2024_9.parquet'],
 '01848E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01910E': ['GLM_2024_9.parquet'],
 '01941E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01754F': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01754E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01545A': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01793H': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01692F': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01599E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01848F': ['GLM_2024_9.parquet'],
 '01841A': ['GLM_2024_9.parquet'],
 '01872A': ['GLM_2024_9.parquet'],
 '01685A': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01887A': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01909F': ['GLM_2024_9.parquet'],
 '01909E': ['GLM_2024_9.parquet'],
 '01552E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01490E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01934A': ['GLM_2024_9.parquet'],
 '01739E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01732A': ['GLM_2024_9.parquet'],
 '01903A': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01592A': ['GLM_2024_9.parquet'],
 '01623A': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01763A': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01630E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01856A': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01832E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01863E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01708E': ['GLM_2024_9.parquet', 'LI_2024_9.parquet'],
 '01779A': ['GLM_2024_9.parquet'],
 '01833E': ['GLM_2024_9.parquet'],
 '01717A': ['GLM_2024_9.parquet'],
 '01693E': ['GLM_2024_9.parquet'],
 '01553E': ['GLM_2024_9.parquet'],
 '01608A': ['GLM_2024_9.parquet'],
 '01561A': ['GLM_2024_9.parquet'],
 '01737A': ['GLM_2024_9.parquet'],
 '01499A': ['GLM_2024_9.parquet'],
 '01500A': ['GLM_2024_9.parquet'],
 '01780A': ['GLM_2024_9.parquet'],
 '01585E': ['GLM_2024_9.parquet'],
 '01725E': ['GLM_2024_9.parquet'],
 '01571E': ['GLM_2024_9.parquet'],
 '01720A': ['GLM_2024_9.parquet'],
 '01712E': ['GLM_2024_9.parquet'],
 '01830A': ['GLM_2024_9.parquet'],
 '01861A': ['GLM_2024_9.parquet'],
 '01721A': ['GLM_2024_9.parquet'],
 '01612A': ['GLM_2024_9.parquet'],
 '01705A': ['GLM_2024_9.parquet'],
 '01891A': ['GLM_2024_9.parquet'],
 '01896E': ['GLM_2024_9.parquet'],
 '01671A': ['GLM_2024_9.parquet'],
 '01702A': ['GLM_2024_9.parquet'],
 '01757E': ['GLM_2024_9.parquet'],
 '01601E': ['GLM_2024_9.parquet'],
 '01492E': ['GLM_2024_9.parquet'],
 '01523E': ['GLM_2024_9.parquet'],
 '01694E': ['GLM_2024_9.parquet'],
 '01756E': ['GLM_2024_9.parquet'],
 '01733A': ['GLM_2024_9.parquet'],
 '01593A': ['GLM_2024_9.parquet'],
 '01562A': ['GLM_2024_9.parquet'],
 '01554E': ['GLM_2024_9.parquet'],
 '01632E': ['GLM_2024_9.parquet'],
 '01772E': ['GLM_2024_9.parquet'],
 '01764A': ['GLM_2024_9.parquet'],
 '01484A': ['GLM_2024_9.parquet'],
 '01842A': ['GLM_2024_9.parquet'],
 '01865E': ['GLM_2024_9.parquet'],
 '01624A': ['GLM_2024_9.parquet'],
 '01834E': ['GLM_2024_9.parquet'],
 '01616E': ['GLM_2024_9.parquet'],
 '01920A': ['GLM_2024_9.parquet'],
 '01881E': ['GLM_2024_9.parquet'],
 '01850E': ['GLM_2024_9.parquet'],
 '01570E': ['GLM_2024_9.parquet'],
 '01578A': ['GLM_2024_9.parquet'],
 '01741E': ['GLM_2024_9.parquet'],
 '01547A': ['GLM_2024_9.parquet'],
 '01539E': ['GLM_2024_9.parquet'],
 '01531A': ['GLM_2024_9.parquet'],
 '01943E': ['GLM_2024_9.parquet'],
 '01904A': ['GLM_2024_9.parquet'],
 '01593B': ['GLM_2024_9.parquet'],
 '01865D': ['GLM_2024_9.parquet'],
 '01554D': ['GLM_2024_9.parquet'],
 '01562B': ['GLM_2024_9.parquet'],
 '01671B': ['GLM_2024_9.parquet'],
 '01523D': ['GLM_2024_9.parquet'],
 '01632D': ['GLM_2024_9.parquet'],
 '01741D': ['GLM_2024_9.parquet'],
 '01710D': ['GLM_2024_9.parquet'],
 '01710E': ['GLM_2024_9.parquet'],
 '01500B': ['GLM_2024_9.parquet'],
 '01570D': ['GLM_2024_9.parquet'],
 '01578B': ['GLM_2024_9.parquet'],
 '01780B': ['GLM_2024_9.parquet'],

Write the earthcare-id -> file dictionary as a parquet file.

In [ ]:
df = pd.Series(earthcare_ids).reset_index()
df.columns = ['earthcare_id', 'files']
df.to_parquet('/Volumes/T7/data/blanka/earthcare_id_mapping.parquet', engine='pyarrow', compression='zstd')

### Collection 2

In [ ]:
def process_col2_nc_to_geoparquet(file_list):
    """
    Reads EarthCARE NC files, expands 2D variables (cpr, subcluster_id) 
    into a flat dataframe, sorts, and saves as GeoParquet.
    """
    dataframes = []
    
    for file_path in file_list:
        try:
            with xr.open_dataset(file_path) as ds:

                df = ds.to_dataframe().reset_index()
                path_obj = Path(file_path)
                earthcare_id = path_obj.stem.split('_')[-1]
                df['earthcare_id'] = earthcare_id
                dataframes.append(df)

        except Exception as e:
            print(f"Skipping {file_path}: {e}")


    print("Concatenating all files...")
    full_df = pd.concat(dataframes, ignore_index=True)

    del dataframes
    gc.collect()

    print("Creating GeoDataFrame...")
    geometry = gpd.points_from_xy(full_df['longitude'], full_df['latitude'])
    full_df.drop(columns=['latitude', 'longitude', 'cpr'], inplace=True)
    gdf = gpd.GeoDataFrame(full_df, geometry=geometry, crs="EPSG:4326")

    del full_df
    gc.collect()

    print("Sorting data...")
    gdf.sort_values(
        by=['geometry', 'time'], 
        inplace=True, 
        ignore_index=True
    )

    return gdf

Process LI files in one go.

In [21]:
output_dir = '/Volumes/T7/data/blanka/C2_parquet/'
source = 'LI'
source_files = [f for f in files2 if source in f]

gdf = process_col2_nc_to_geoparquet(source_files)

gdf.to_parquet(
    output_dir + f'{source}_C2.parquet',
    engine='pyarrow',
    compression='zstd',
    write_covering_bbox=True, 
    schema_version='1.1.0'
)

Processing 2083 files...
Concatenating all files...
Creating GeoDataFrame...
Sorting data...

Process GLM files in one go.

In [22]:
output_dir = '/Volumes/T7/data/blanka/C2_parquet/'
source = 'GLM'
source_files = [f for f in files2 if source in f]

gdf = process_col2_nc_to_geoparquet(source_files)

gdf.to_parquet(
    output_dir + f'{source}_C2.parquet',
    engine='pyarrow',
    compression='zstd',
    write_covering_bbox=True, 
    schema_version='1.1.0'
)

Processing 2191 files...
Concatenating all files...
Creating GeoDataFrame...
Sorting data...

### Collection 3

Process the collection 3 files.

In [ ]:
import json
import pandas as pd
import geopandas as gpd
import numpy as np
from datetime import timedelta

def transform_json_to_parquet(json_file_path):

    with open(json_file_path, 'r') as f:
        content = json.load(f)
    
    data = content['data']

    df_summary = pd.DataFrame(data).drop(
        columns=['minute_counts', 'minute_mean_lat', 'minute_mean_lon']
    )
    
    # Convert types
    df_summary['peak_datetime'] = pd.to_datetime(df_summary['peak_datetime'])
    gdf_summary = gpd.GeoDataFrame(
        df_summary,
        geometry=gpd.points_from_xy(df_summary['peak_lon'], df_summary['peak_lat']),
        crs="EPSG:4326"
    )
    
    # the Evolution GeoDataFrame (Detail) ---
    evolution_rows = []
    
    for entry in data:
        common_ids = {
            'orbit_frame': entry['orbit_frame'],
            'parent_cluster_id': entry['parent_cluster_id'],
            'cluster_id': entry['cluster_id'],
            'peak_datetime': pd.to_datetime(entry['peak_datetime'])
        }
        
        minutes = entry['minute_counts'].keys()
        
        for m_str in minutes:
            minute_offset = int(m_str)
            abs_time = common_ids['peak_datetime'] + timedelta(minutes=minute_offset)
        
            row = common_ids.copy()
            row['minute_offset'] = minute_offset
            row['absolute_time'] = abs_time
            row['li_count'] = entry['minute_counts'][m_str]
            row['latitude'] = entry['minute_mean_lat'][m_str]
            row['longitude'] = entry['minute_mean_lon'][m_str]
            
            evolution_rows.append(row)
            
    df_evolution = pd.DataFrame(evolution_rows)
    
    # Create Geometry (Track Location)
    gdf_evolution = gpd.GeoDataFrame(
        df_evolution,
        geometry=gpd.points_from_xy(df_evolution['longitude'], df_evolution['latitude']),
        crs="EPSG:4326"
    )
    
    gdf_evolution = gdf_evolution.sort_values(by=['parent_cluster_id', 'cluster_id', 'absolute_time', ])

    return gdf_summary, gdf_evolution

In [34]:
json_file_path = '/Volumes/T7/data/blanka/C3_EarthCARE_lightning_storm_catalogue.json'

gdf_summary, gdf_evolution = transform_json_to_parquet(json_file_path)

In [35]:
gdf_summary.to_parquet('/Volumes/T7/data/blanka/C3_parquet/gdf_summary.pq', index=False)
gdf_evolution.to_parquet('/Volumes/T7/data/blanka/C3_parquet/gdf_evolution.pq', index=False)

# Tests and Asserts

In [ ]:

import glob
import xarray as xr
import geopandas as gpd
import numpy as np
import os
import re

files = sorted(glob.glob('/Volumes/T7/data/blanka/C1/*.nc'))

In [37]:
files

['/Volumes/T7/data/blanka/C1/GLM_20240801T041007Z_20240801T051832Z_33_0_01000B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T052943Z_20240801T074235Z_60975_423_01001A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T054120Z_20240801T075418Z_48011_16_01001B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T070219Z_20240801T091519Z_298341_173_01002A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T115405Z_20240801T135135Z_276_0_01005A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T132449Z_20240801T153658Z_5447_0_01006B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T153508Z_20240801T172844Z_71_0_01007E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T162830Z_20240801T175403Z_69_0_01007F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T170444Z_20240801T191707Z_19282_77_01008E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T182521Z_20240801T203818Z_62850_0_01009D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T183710Z_20240801T204957Z_51240_41_01009E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T195804Z_20240801T221058Z_24615_0_01010D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240801T200943Z_20240801T222239Z_36763_0_01010E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T042739Z_20240802T064032Z_19504_136_01015H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T061203Z_20240802T082437Z_16436_0_01017A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T062320Z_20240802T083639Z_150277_1094_01017B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T075608Z_20240802T100914Z_5058_0_01018B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T091703Z_20240802T112912Z_2566_0_01019A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T103813Z_20240802T125037Z_14455_0_01019H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T122448Z_20240802T143518Z_2738_50_01021A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T162615Z_20240802T182710Z_5124_0_01023F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T170425Z_20240802T182636Z_1003_0_01023E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T174643Z_20240802T195918Z_61421_0_01024E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T190721Z_20240802T212019Z_68831_0_01025D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T191919Z_20240802T213158Z_115218_34_01025E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240802T204006Z_20240802T225258Z_19897_39_01026D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T050919Z_20240803T072239Z_295448_1052_01031H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T052155Z_20240803T073414Z_4393_0_01032A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T053307Z_20240803T074554Z_11114_0_01032B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T065417Z_20240803T090636Z_24049_0_01033A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T070543Z_20240803T091838Z_43788_0_01033B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T083147Z_20240803T103040Z_816_0_01034A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T112059Z_20240803T133209Z_4335_0_01035H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T165601Z_20240803T190837Z_30101_43_01039E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T181639Z_20240803T202938Z_239276_1525_01040D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T182839Z_20240803T204119Z_110888_109_01040E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T194923Z_20240803T220217Z_29190_270_01041D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T200127Z_20240803T221355Z_14378_322_01041E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T212208Z_20240803T233455Z_4884_0_01042D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240803T214523Z_20240803T235558Z_1695_0_01042F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T025943Z_20240804T045928Z_204_0_01046A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T032633Z_20240804T051646Z_391_0_01046B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T041907Z_20240804T063113Z_12393_14_01046H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T044530Z_20240804T065410Z_2840_0_01047B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T060325Z_20240804T081550Z_28468_0_01048A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T061621Z_20240804T082742Z_10749_0_01048B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T073559Z_20240804T094824Z_30073_57_01049A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T074739Z_20240804T100035Z_12961_0_01049B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T121746Z_20240804T142632Z_1321_0_01052A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T172605Z_20240804T193901Z_3482_0_01055D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T173800Z_20240804T195039Z_94232_8_01055E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T190045Z_20240804T211118Z_9034_38_01056D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T191054Z_20240804T212318Z_20189_0_01056E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T203131Z_20240804T224417Z_21612_123_01057D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T205803Z_20240804T224800Z_4081_0_01057F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240804T233717Z_20240805T014804Z_776_0_01059D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T025047Z_20240805T042949Z_531_0_01061B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T051243Z_20240805T072537Z_23123_13_01063A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T052420Z_20240805T073652Z_14952_3_01063B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T064521Z_20240805T085758Z_68242_804_01064A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T065700Z_20240805T090956Z_14633_122_01064B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T082327Z_20240805T102448Z_424_0_01065A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T082922Z_20240805T104236Z_9963_0_01065B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T180759Z_20240805T202054Z_19456_87_01071D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T182001Z_20240805T203238Z_77829_398_01071E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T194438Z_20240805T215327Z_5657_108_01072D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T195230Z_20240805T220519Z_11624_92_01072E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240805T211327Z_20240805T232615Z_3741_0_01073D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T055439Z_20240806T080719Z_303582_318_01079A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T060627Z_20240806T081917Z_14244_0_01079B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T073839Z_20240806T095003Z_4764_0_01080B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T084807Z_20240806T110053Z_10381_0_01080H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T121422Z_20240806T140940Z_356_0_01083A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T133808Z_20240806T154812Z_1474_12_01084A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T160804Z_20240806T181922Z_4614_0_01085F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T171723Z_20240806T192545Z_5458_0_01086D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T172907Z_20240806T194158Z_50975_197_01086E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T185005Z_20240806T210259Z_50196_78_01087D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T190141Z_20240806T211435Z_6100_89_01087E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T202239Z_20240806T223539Z_50430_258_01088D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T203425Z_20240806T223444Z_4671_0_01088E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T204611Z_20240806T225506Z_3400_88_01088F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T222806Z_20240807T000658Z_262_0_01089F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240806T235040Z_20240807T014710Z_1122_0_01090E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T034411Z_20240807T055148Z_1232_0_01093B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T035606Z_20240807T052223Z_71_0_01093A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T045222Z_20240807T070453Z_33315_0_01093H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T051644Z_20240807T072803Z_9624_0_01094B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T063620Z_20240807T084917Z_28086_136_01095A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T070422Z_20240807T075003Z_7839_131_01095B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T082124Z_20240807T103334Z_8078_0_01096B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T163819Z_20240807T185119Z_47511_424_01101E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T165015Z_20240807T190232Z_8208_0_01101F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T181101Z_20240807T202356Z_17632_0_01102E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T194343Z_20240807T215619Z_7841_0_01103E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240807T210423Z_20240807T231717Z_758_0_01104D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240808T054540Z_20240808T075835Z_16870_0_01110A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240808T055722Z_20240808T081006Z_27776_0_01110B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240808T071825Z_20240808T093050Z_24111_277_01111A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240808T073003Z_20240808T094245Z_7569_0_01111B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240808T101217Z_20240808T122054Z_2187_78_01112H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240808T134210Z_20240808T153813Z_746_0_01115A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240808T172025Z_20240808T193259Z_112152_181_01117E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240808T184129Z_20240808T205355Z_46621_0_01118D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240808T185254Z_20240808T210538Z_29966_0_01118E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240808T201339Z_20240808T222636Z_31250_156_01119D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T033536Z_20240809T054657Z_3662_0_01124B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T045505Z_20240809T070735Z_7109_0_01125A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T062728Z_20240809T083925Z_12964_0_01126A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T063859Z_20240809T085159Z_415217_2632_01126B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T081152Z_20240809T102347Z_28308_3_01127B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T085607Z_20240809T095920Z_378_0_01127A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T150834Z_20240809T172052Z_5907_0_01131F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T163137Z_20240809T184219Z_3385_0_01132E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T164144Z_20240809T183033Z_418_0_01132F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T175001Z_20240809T200314Z_5369_66_01133D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T180159Z_20240809T201439Z_116328_668_01133E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T192241Z_20240809T212836Z_3674_0_01134D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T193445Z_20240809T214718Z_56541_0_01134E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240809T205520Z_20240809T230816Z_8795_8_01135D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T024259Z_20240810T045545Z_23721_0_01139B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T040515Z_20240810T061455Z_2615_0_01140A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T053639Z_20240810T074917Z_90342_202_01141A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T054800Z_20240810T080038Z_37840_0_01141B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T070955Z_20240810T092009Z_1177_0_01142A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T072050Z_20240810T093336Z_10926_0_01142B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T132004Z_20240810T153136Z_12716_0_01146A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T171101Z_20240810T192359Z_78479_0_01148E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T171451Z_20240810T181207Z_752_0_01148D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T183200Z_20240810T204459Z_201011_539_01149D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T184342Z_20240810T205619Z_71257_0_01149E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T200421Z_20240810T221718Z_41917_322_01150D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T201620Z_20240810T222859Z_44373_0_01150E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240810T213702Z_20240810T234947Z_959_0_01151D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240811T044156Z_20240811T064607Z_10117_0_01155H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240811T044539Z_20240811T065814Z_27970_283_01156A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240811T061822Z_20240811T083048Z_41715_0_01157A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240811T080219Z_20240811T101517Z_112552_930_01158B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240811T162153Z_20240811T183258Z_3594_0_01163E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240811T174121Z_20240811T195251Z_5681_1_01164D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240811T175239Z_20240811T200538Z_44838_42_01164E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240811T191320Z_20240811T212637Z_80147_0_01165D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240811T192649Z_20240811T213749Z_6278_0_01165E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240811T204600Z_20240811T225859Z_75439_78_01166D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T034345Z_20240812T054426Z_139_0_01170H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T052726Z_20240812T073958Z_21812_10_01172A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T053840Z_20240812T075159Z_41636_127_01172B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T065943Z_20240812T091229Z_27665_0_01173A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T071132Z_20240812T091130Z_6329_0_01173B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T154103Z_20240812T175322Z_14322_36_01178F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T170142Z_20240812T191438Z_25177_0_01179E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T182223Z_20240812T203539Z_62138_0_01180D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T183420Z_20240812T204654Z_26140_0_01180E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T195516Z_20240812T220750Z_947_0_01181D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T200659Z_20240812T221937Z_12438_0_01181E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240812T212750Z_20240812T233853Z_2018_0_01182D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T025353Z_20240813T050435Z_9552_0_01185H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T044743Z_20240813T065959Z_5697_0_01187B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T060907Z_20240813T082130Z_34177_169_01188A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T074119Z_20240813T095419Z_104269_70_01189A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T075300Z_20240813T100558Z_143222_707_01189B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T103516Z_20240813T124721Z_1917_0_01190H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T122144Z_20240813T143011Z_1800_0_01192A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T145018Z_20240813T165301Z_132_0_01193F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T161118Z_20240813T182315Z_1306_0_01194E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T173124Z_20240813T194416Z_32355_7_01195D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T174303Z_20240813T195559Z_21524_51_01195E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T190400Z_20240813T211659Z_64620_248_01196D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T191539Z_20240813T212839Z_74081_5196_01196E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240813T203643Z_20240813T224939Z_62231_43_01197D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T040324Z_20240814T060748Z_757_0_01202B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T051739Z_20240814T073017Z_84371_571_01203A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T053121Z_20240814T074209Z_274_0_01203B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T065050Z_20240814T090228Z_6216_44_01204A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T070140Z_20240814T091458Z_125753_833_01204B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T082331Z_20240814T103513Z_1051_0_01205A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T111621Z_20240814T132904Z_10665_0_01206H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T130048Z_20240814T151317Z_31012_0_01208A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T165202Z_20240814T190435Z_47602_763_01210E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T181338Z_20240814T202532Z_7713_0_01211D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T182439Z_20240814T203718Z_27773_0_01211E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T194550Z_20240814T215819Z_5146_50_01212D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T195704Z_20240814T220959Z_6431_41_01212E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T213019Z_20240814T231539Z_131_0_01213E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240814T233042Z_20240815T010845Z_290_0_01214F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T031435Z_20240815T044834Z_120_0_01216H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T043801Z_20240815T065058Z_9230_5_01218B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T055901Z_20240815T081157Z_84653_0_01219A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T073146Z_20240815T094415Z_6030_5_01220A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T074455Z_20240815T095607Z_1712_0_01220B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T090449Z_20240815T111428Z_807_0_01221A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T172146Z_20240815T193416Z_1337_0_01226D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T185403Z_20240815T210716Z_45278_0_01227D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T190602Z_20240815T211839Z_56830_109_01227E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T202647Z_20240815T223935Z_7896_0_01228D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240815T203917Z_20240815T215057Z_803_0_01228E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T033523Z_20240816T054747Z_52725_82_01233A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T043138Z_20240816T055951Z_730_0_01233B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T050739Z_20240816T072020Z_45684_0_01234A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T064019Z_20240816T085318Z_7585_37_01235A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T065205Z_20240816T090459Z_26609_0_01235B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T114257Z_20240816T132418Z_1808_0_01238A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T164217Z_20240816T185459Z_14111_0_01241E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T180552Z_20240816T201559Z_1940_0_01242D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T181444Z_20240816T202732Z_18771_18_01242E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T193519Z_20240816T214839Z_16362_219_01243D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T194720Z_20240816T215957Z_20282_0_01243E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T210800Z_20240816T232057Z_4441_0_01244D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240816T212031Z_20240816T230719Z_928_0_01244E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T040552Z_20240817T061436Z_1792_0_01248H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T043646Z_20240817T062835Z_132_0_01249B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T054859Z_20240817T080158Z_228139_400_01250A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T060046Z_20240817T081331Z_11633_0_01250B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T072142Z_20240817T093437Z_26497_39_01251A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T073320Z_20240817T094619Z_30009_0_01251B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T085457Z_20240817T110641Z_2606_0_01252A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T122056Z_20240817T135910Z_569_5_01253H.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T133210Z_20240817T154426Z_5442_0_01255A.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T153954Z_20240817T174139Z_249_0_01256D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T160229Z_20240817T181516Z_21638_0_01256F.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T171254Z_20240817T192438Z_3597_117_01257D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T172321Z_20240817T193619Z_133276_402_01257E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T184359Z_20240817T205719Z_303752_137_01258D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T185600Z_20240817T210839Z_77171_25_01258E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T201639Z_20240817T222938Z_33913_250_01259D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T202843Z_20240817T223735Z_497_0_01259E.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240817T215815Z_20240817T235734Z_260_0_01260D.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240818T034046Z_20240818T054852Z_987_0_01264B.nc',
 '/Volumes/T7/data/blanka/C1/GLM_20240818T045740Z_20240818T071026Z_124639_0_01265A.nc',

In [ ]:
def extract_file_info(file_path):
    filename = os.path.basename(file_path)
    parts = filename.split('_')
    source = parts[0]
    date_str = parts[1]
    year = int(date_str[:4])
    month = int(date_str[4:6])
    return source, year, month

np.random.seed(42)
rf = np.random.choice(files)  # Randomly select a file for testing
t, y, m = extract_file_info(rf)
t,y,m

('LI', 2025, 1)

In [39]:
new = gpd.read_parquet(f'/Volumes/T7/data/blanka/C1_parquet/{t}_{y}_{m}.parquet')
new

,group_id,group_time,latitude,longitude,radiance,flash_id,parallax_corrected_lat,parallax_corrected_lon,ec_time_diff,parent_cluster_id,cluster_id,distance_from_nadir,earthcare_id,geometry
0,273053035,2025-01-08 07:38:16.413699968,-54.901802,-71.552704,41.0,38701535,NaN,NaN,-9223372036854775808,-1,NaN,NaN,03490H,POINT (-71.5527 -54.9018)
1,273053033,2025-01-08 07:38:16.411699968,-54.915302,-71.547302,26.0,38701535,NaN,NaN,-9223372036854775808,-1,NaN,NaN,03490H,POINT (-71.5473 -54.9153)
2,273053034,2025-01-08 07:38:16.412700032,-54.885601,-71.460899,55.0,38701535,NaN,NaN,-9223372036854775808,-1,NaN,NaN,03490H,POINT (-71.4609 -54.8856)
3,272771951,2025-01-08 07:04:53.109299968,-54.623703,-71.439301,5.0,38571823,NaN,NaN,-9223372036854775808,-1,NaN,NaN,03490H,POINT (-71.4393 -54.6237)
4,273071260,2025-01-08 07:40:36.372400000,-54.580502,-70.980301,5.5,38710401,NaN,NaN,-9223372036854775808,-1,NaN,NaN,03490H,POINT (-70.9803 -54.5805)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14453971,601187,2025-01-20 12:03:35.710300032,-58.746601,18.665100,9.0,215473,-58.617088,18.566853,108790406016,-1,NaN,NaN,03680F,POINT (18.6651 -58.7466)
14453972,223186241,2025-01-06 11:06:01.514499968,-55.088100,24.780602,21.0,26807039,NaN,NaN,-9223372036854775808,-1,NaN,NaN,03462F,POINT (24.7806 -55.0881)
14453973,223186242,2025-01-06 11:06:01.514499968,-55.166401,24.429600,14.5,26807039,NaN,NaN,-9223372036854775808,-1,NaN,NaN,03462F,POINT (24.4296 -55.1664)
14453974,223186240,2025-01-06 11:06:01.514499968,-55.036800,25.031700,10.5,26807039,NaN,NaN,-9223372036854775808,-1,NaN,NaN,03462F,POINT (25.0317 -55.0368)
14453975,18018465,2025-01-24 23:38:48.697299968,-38.731503,30.450602,197.0,3372871,NaN,NaN,-9223372036854775808,-1,NaN,NaN,03750H,POINT (30.4506 -38.7315)

In [ ]:
orig = xr.open_dataset(rf, decode_timedelta=True)
orig

<xarray.Dataset> Size: 2MB
Dimensions:                 (groups: 41268)
Dimensions without coordinates: groups
Data variables:
    group_id                (groups) uint64 330kB ...
    group_time              (groups) datetime64[ns] 330kB ...
    latitude                (groups) float32 165kB ...
    longitude               (groups) float32 165kB ...
    radiance                (groups) float32 165kB ...
    flash_id                (groups) uint32 165kB ...
    parallax_corrected_lat  (groups) float32 165kB ...
    parallax_corrected_lon  (groups) float32 165kB ...
    ec_time_diff            (groups) int64 330kB ...
    parent_cluster_id       (groups) int16 83kB ...
    cluster_id              (groups) float32 165kB ...
    distance_from_nadir     (groups) float32 165kB ...
Attributes: (12/13)
    Conventions:          CF-1.8
    title:                MTG-LI to EarthCARE collocated data
    summary:              Subset of MTG-LI L2 group product, collocated to Ea...
    institution:          European Space Agency (ESA)
    history:              Created on 2026-01-08
    source:               EarthCARE MSI/CPR + EUMETSAT MTG Lightning Imager (...
    ...                   ...
    geospatial_lat_min:   -14.45580005645752
    geospatial_lat_max:   3.6288001537323
    geospatial_lon_min:   4.619699954986572
    geospatial_lon_max:   9.250200271606445
    time_coverage_start:  2025-01-18T12:20:04Z
    time_coverage_end:    2025-01-18T14:39:57Z

In [42]:
for d in orig.data_vars:

    assert orig[d].dropna(dim='groups').isin(new[d].values).all().values

In [43]:
new[new.group_id == orig['group_id'].values[0]]

,group_id,group_time,latitude,longitude,radiance,flash_id,parallax_corrected_lat,parallax_corrected_lon,ec_time_diff,parent_cluster_id,cluster_id,distance_from_nadir,earthcare_id,geometry
5157450,93530770,2025-01-18 14:30:00.817600,2.3787,8.9505,11.5,14136553,NaN,NaN,-9223372036854775808,10,NaN,NaN,03650E,POINT (8.9505 2.3787)

In [53]:
subset = new[new.group_id.isin(orig['group_id'].values) & new.group_time.isin(orig['group_time'].values)]
subset = subset.sort_values(by='group_id').reset_index(drop=True)
orig = orig.sortby("group_id")


columns_to_check = ['group_id','latitude', 'longitude', 'radiance', 'flash_id', 'parent_cluster_id', 'cluster_id', 'distance_from_nadir'] #  'group_time', 
for c in columns_to_check:
    assert np.isclose(subset[c], orig[c].values, equal_nan=True).all()